import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://middesk.com">Middesk</a> Example Implementation
        </h1>

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        <div className={styles.grid}>
          <Link href="/form">
            <a className={styles.card}>
              <h2>Start Application &rarr;</h2>
              <p>Start your business bank account application process</p>
            </a>
          </Link>
          
          <Link href="/applications">
            <a className={styles.card}>
              <h2>Application Status &rarr;</h2>
              <p>Check the statuses of your business bank account applications</p>
            </a>
          </Link>

          {/* <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://middesk.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by &nbsp;<strong>Middesk</strong>
        </a>
      </footer>
    </div>
  )
}
